services:
  api:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - neo4j
      - chromadb
      - mongodb
      # Removed ingestion dependency - API runs independently
    command: ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    networks:
      - app-network
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - MONGODB_HOST=mongodb
      - MONGODB_USER=user
      - MONGODB_PASSWORD=password
      - MONGODB_DB=research_db

  ingestion:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - neo4j
      - chromadb
      - mongodb
    command: |
      sh -c "
        echo '⏳ Waiting for databases to be ready...' &&
        sleep 45 &&
        echo '🔄 Starting PDF ingestion...' &&
        python src/utils/ingestion_pipeline.py &&
        echo '✅ Ingestion completed!'
      "
    networks:
      - app-network
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - MONGODB_HOST=mongodb
      - MONGODB_USER=user
      - MONGODB_PASSWORD=password
      - MONGODB_DB=research_db
    restart: "no"  # Run once and stop

  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_server_config_strict__validation_enabled=false
    networks:
      - app-network

  chromadb:
    image: chromadb/chroma:0.6.3
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    volumes:
      - chromadb_data:/chroma
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=research_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://user:password@mongodb:27017/
    networks:
      - app-network
    depends_on:
      - mongodb

networks:
  app-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  chromadb_data:
  mongo-data: